fix: multimint version conflict
```shell
$ cargo build
    Updating crates.io index
error: failed to select a version for `multimint`.
    ... required by package `clientd-stateless v0.3.5 (/home/henrique/Projects/fedimint-clientd/clientd-stateless)`
versions that meet the requirements `^0.3.5` (locked to 0.3.5) are: 0.3.5

all possible versions conflict with previously selected packages.

  previously selected package `multimint v0.3.6`
    ... which satisfies dependency `multimint = "^0.3.6"` of package `fedimint-clientd v0.3.6 (/home/henrique/Projects/fedimint-clientd/fedimint-clientd)`

failed to select a version for `multimint` which could resolve this conflict
```